In [1]:
import random
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# weather example with Markov Chains and Monte Carlo simulation

# define the Markov probabilities (R - rainy, R1 - rainy day today R2 - rainy the next day, S - sunny, S1 ....)
P_S2_R1 = 0.5 # probability of sunny the next day when raining today
P_R2_R1 = 0.5 # probability of rainy the next day when raining today
P_S2_S1 = 0.9 # probability of sunny the next day when sunny today
P_R2_S1 = 0.1 # probability of rainy the next day when sunny today

# want to find P(S) and P(R), from the Markov probabilities we can create Markov chains by Monte Carlo sampling

In [36]:
# start with some initial state where R1 and S1 are equal probability

# define an empty chain (R = 0, S = 1)
MC = [round(random.uniform(0, 1))]
nSamples = 20000
for i in range(nSamples):

    # draw a sample from a unform distribution
    r = random.uniform(0, 1)

    # if the current sample is S (1) then with 90-10 of being S-R
    if MC[i] == 1: # sun
        if r <= P_R2_S1: # 0.1
            MC.append(0)
        else:
            # P_S2_S1 0.9
            MC.append(1)
    # if the current sample is R (0) then with 50-50 of being S-R
    if MC[i] == 0: # rain
        if r <= P_R2_R1: # 0.5
            MC.append(0)
        else:
            # P_S2_R1 0.5
            MC.append(1)

#print(MC)
print(sum(MC) / nSamples, 1 - sum(MC) / nSamples)




0.82985 0.17015000000000002


In [83]:
# Markov transition matrix

A = np.array([[0.9, 0.5], [0.1, 0.5]])
print(A, "Transition from Column to row")



[[0.9 0.5]
 [0.1 0.5]] Transition from Column to row


In [84]:
def markovTransitionProbability(matrix, initialState, convergenceSensitivity=1e-8, maxNumberOfTransitions=100):
    tmp = matrix

    for _ in range(maxNumberOfTransitions):
        
        matrix = matrix.dot(matrix)
        if np.linalg.norm(tmp - matrix) < convergenceSensitivity:
            break
        tmp = matrix

    return matrix.dot(initialState), matrix
    #return matrix.dot(initialState)

s, T = markovTransitionProbability(matrix=A, initialState=np.array([1, 0]).T, maxNumberOfTransitions=55)

print(s)
print(T)

[0.83333333 0.16666667]
[[0.83333333 0.83333333]
 [0.16666667 0.16666667]]


In [96]:
np.linalg.pinv(T.T).dot(s)

array([0.57692308, 0.11538462])

In [97]:
T.T.dot(T)

array([[0.72222222, 0.72222222],
       [0.72222222, 0.72222222]])