In [1]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

In [2]:
# P(S) , probability of the season
thetas_season = tf.constant([0.25] * 4) # prob spring, prob summer, prob winter, prob autumn

In [5]:
# P(W|S), probability of good weather given the season, which are assumed here to be observed (estimated)
thetas_weather = tf.constant([0.4, 0.9, 0.5, 0.3]) # 

In [6]:
def season_weather_model(season_probs, season_to_weather_probs):
    season = yield tfd.JointDistributionCoroutine.Root(tfd.Categorical(probs=season_probs, name="seasons"))
    # return a Bernoulli 
    weather = yield tfd.Bernoulli(probs=season_to_weather_probs[season], name="weather") 

In [7]:
mixture_joint = tfd.JointDistributionCoroutineAutoBatched(
    lambda : season_weather_model(thetas_season, thetas_weather)
)

In [9]:
mixture_joint.sample()

StructTuple(
  seasons=<tf.Tensor: shape=(), dtype=int32, numpy=3>,
  weather=<tf.Tensor: shape=(), dtype=int32, numpy=0>
)

In [10]:
mixture_joint.prob([0, 1])

<tf.Tensor: shape=(), dtype=float32, numpy=0.099999994>

In [16]:
prob = tfd.Bernoulli(probs=0.3)
for _ in range(10):
    print(prob.sample())

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
